name = "temp-email"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[vars]
DEFAULT_DOMAINS = ["aifxo.com"]
DOMAINS = ["aifxo.com"]
JWT_SECRET = "change-this-to-a-long-random-secret"
ADMIN_PASSWORDS = ["Liao520a."]
ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true
[[d1_databases]]
binding = "DB"
database_name = "temp_email"
database_id = "863b5e29-d7a4-44ae-93e8-40248e0d01e8"
